import { pgTable, serial, integer, text, timestamp, pgEnum, decimal, boolean, jsonb, varchar, index, uniqueIndex } from "drizzle-orm/pg-core";
import { clientsTable } from "./clients";

export const wpFileCategory = pgEnum("wp_file_category", [
  "financial_statements",
  "trial_balance",
  "general_ledger",
  "bank_statement",
  "sales_tax_return",
  "tax_notice",
  "schedule",
  "annexure",
  "other",
]);

export const wpFileFormat = pgEnum("wp_file_format", [
  "excel",
  "pdf",
  "image",
]);

export const wpSourceType = pgEnum("wp_source_type", [
  "native_text_pdf",
  "ocr_pdf",
  "image_ocr",
  "excel_native",
  "manual_entry",
]);

export const wpExtractionStatus = pgEnum("wp_extraction_status", [
  "pending",
  "processing",
  "completed",
  "failed",
]);

export const wpHeadStatus = pgEnum("wp_head_status", [
  "locked",
  "ready",
  "in_progress",
  "validating",
  "review",
  "approved",
  "exported",
  "completed",
]);

export const wpExceptionStatus = pgEnum("wp_exception_status", [
  "open",
  "cleared",
  "override_approved",
  "deferred",
  "not_applicable",
]);

export const wpSessionStatus = pgEnum("wp_session_status", [
  "upload",
  "extraction",
  "data_sheet",
  "arranged_data",
  "variables",
  "wp_listing",
  "generation",
  "audit_chain",
  "review",
  "export",
  "completed",
]);

export const wpEntityType = pgEnum("wp_entity_type", [
  "pvt_ltd",
  "listed",
  "smc",
  "llp",
  "bank",
  "insurance",
  "ngo",
  "soe",
  "branch",
  "association",
  "trust",
  "sole_proprietor",
  "partnership",
  "other",
]);

export const wpReportingFramework = pgEnum("wp_reporting_framework", [
  "IFRS",
  "IFRS_for_SMEs",
  "AFRS",
  "Custom",
]);

export const wpEngagementType = pgEnum("wp_engagement_type", [
  "statutory_audit",
  "internal_audit",
  "review_engagement",
  "agreed_upon_procedures",
  "compilation",
  "tax_audit",
  "forensic_audit",
  "special_purpose",
  "other",
]);

export const wpRiskLevel = pgEnum("wp_risk_level", [
  "low",
  "medium",
  "high",
  "critical",
]);

export const wpSeverity = pgEnum("wp_severity", [
  "critical",
  "high",
  "medium",
  "low",
  "info",
]);

export const wpSessionsTable = pgTable("wp_sessions", {
  id: serial("id").primaryKey(),
  clientId: integer("client_id").references(() => clientsTable.id),
  clientName: text("client_name").notNull(),
  engagementYear: text("engagement_year").notNull(),
  entityType: text("entity_type"),
  ntn: text("ntn"),
  strn: text("strn"),
  periodStart: text("period_start"),
  periodEnd: text("period_end"),
  reportingFramework: text("reporting_framework").default("IFRS"),
  engagementType: text("engagement_type").default("statutory_audit"),
  engagementContinuity: text("engagement_continuity").default("first_time"),
  industryType: text("industry_type"),
  groupAuditFlag: boolean("group_audit_flag").default(false),
  itEnvironmentType: text("it_environment_type"),
  taxStatusFlags: text("tax_status_flags"),
  specialConditions: text("special_conditions"),
  auditFirmName: text("audit_firm_name"),
  auditFirmLogo: text("audit_firm_logo"),
  preparerId: integer("preparer_id"),
  preparerName: text("preparer_name"),
  preparerIds: text("preparer_ids"),
  preparerNames: text("preparer_names"),
  reviewerId: integer("reviewer_id"),
  reviewerName: text("reviewer_name"),
  approverId: integer("approver_id"),
  approverName: text("approver_name"),
  eqcrId: integer("eqcr_id"),
  eqcrName: text("eqcr_name"),
  status: wpSessionStatus("status").notNull().default("upload"),
  currentHeadIndex: integer("current_head_index").default(0),
  createdBy: integer("created_by"),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_sessions_client_id_idx").on(t.clientId),
  index("wp_sessions_status_idx").on(t.status),
  index("wp_sessions_created_by_idx").on(t.createdBy),
  index("wp_sessions_engagement_year_idx").on(t.engagementYear),
]);

export const wpUploadedFilesTable = pgTable("wp_uploaded_files", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  fileName: text("file_name").notNull(),
  originalName: text("original_name").notNull(),
  fileSize: integer("file_size"),
  mimeType: text("mime_type"),
  category: wpFileCategory("category").notNull(),
  format: wpFileFormat("format").notNull(),
  sourceType: wpSourceType("source_type"),
  pageCount: integer("page_count"),
  sheetCount: integer("sheet_count"),
  isValid: boolean("is_valid").default(true),
  validationErrors: text("validation_errors"),
  fileData: text("file_data"),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_uploaded_files_session_id_idx").on(t.sessionId),
  index("wp_uploaded_files_category_idx").on(t.category),
]);

export const wpExtractionRunsTable = pgTable("wp_extraction_runs", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  fileId: integer("file_id").references(() => wpUploadedFilesTable.id, { onDelete: "cascade" }),
  status: wpExtractionStatus("extraction_status").notNull().default("pending"),
  sourceType: wpSourceType("source_type"),
  totalPages: integer("total_pages"),
  processedPages: integer("processed_pages").default(0),
  rawText: text("raw_text"),
  structuredData: jsonb("structured_data"),
  errorMessage: text("error_message"),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_extraction_runs_session_id_idx").on(t.sessionId),
  index("wp_extraction_runs_file_id_idx").on(t.fileId),
  index("wp_extraction_runs_status_idx").on(t.status),
]);

export const wpExtractedFieldsTable = pgTable("wp_extracted_fields", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  extractionRunId: integer("extraction_run_id").references(() => wpExtractionRunsTable.id, { onDelete: "cascade" }),
  category: text("category").notNull(),
  fieldName: text("field_name").notNull(),
  extractedValue: text("extracted_value"),
  finalValue: text("final_value"),
  confidence: decimal("confidence", { precision: 5, scale: 2 }),
  sourceFile: text("source_file"),
  sourceSheet: text("source_sheet"),
  sourcePageNo: integer("source_page_no"),
  isOverridden: boolean("is_overridden").default(false),
  isApproved: boolean("is_approved").default(false),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_extracted_fields_session_id_idx").on(t.sessionId),
  index("wp_extracted_fields_run_id_idx").on(t.extractionRunId),
  index("wp_extracted_fields_category_idx").on(t.category),
]);

export const wpArrangedDataTable = pgTable("wp_arranged_data", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  tab: text("tab").notNull(),
  rowIndex: integer("row_index").notNull().default(0),
  sourceFile: text("source_file"),
  sourceSheetPage: text("source_sheet_page"),
  fieldName: text("field_name").notNull(),
  extractedValue: text("extracted_value"),
  confidence: decimal("confidence", { precision: 5, scale: 2 }),
  overrideValue: text("override_value"),
  finalApprovedValue: text("final_approved_value"),
  isApproved: boolean("is_approved").default(false),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_arranged_data_session_id_idx").on(t.sessionId),
  index("wp_arranged_data_tab_idx").on(t.sessionId, t.tab),
]);

export const wpVariableDefinitionsTable = pgTable("wp_variable_definitions", {
  id: serial("id").primaryKey(),
  variableCode: varchar("variable_code", { length: 100 }).notNull().unique(),
  variableGroup: text("variable_group").notNull(),
  variableSubgroup: text("variable_subgroup"),
  variableName: text("variable_name").notNull(),
  variableLabel: text("variable_label").notNull(),
  description: text("description"),
  dataType: text("data_type").notNull().default("text"),
  inputMode: text("input_mode").default("text"),
  dropdownOptionsJson: jsonb("dropdown_options_json"),
  defaultValue: text("default_value"),
  mandatoryFlag: boolean("mandatory_flag").default(false),
  editableFlag: boolean("editable_flag").default(true),
  aiExtractableFlag: boolean("ai_extractable_flag").default(false),
  reviewRequiredFlag: boolean("review_required_flag").default(false),
  standardReference: text("standard_reference"),
  pakistanReference: text("pakistan_reference"),
  affectsModulesJson: jsonb("affects_modules_json"),
  affectsWorkingPapersJson: jsonb("affects_working_papers_json"),
  displayOrder: integer("display_order").default(0),
  activeFlag: boolean("active_flag").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const wpVariablesTable = pgTable("wp_variables", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  variableCode: varchar("variable_code", { length: 100 }).notNull(),
  category: text("category").notNull(),
  variableName: text("variable_name").notNull(),
  autoFilledValue: text("auto_filled_value"),
  userEditedValue: text("user_edited_value"),
  finalValue: text("final_value"),
  rawExtractedValue: text("raw_extracted_value"),
  normalizedValue: text("normalized_value"),
  confidence: decimal("confidence", { precision: 5, scale: 2 }),
  sourceType: text("source_type"),
  sourceFileId: integer("source_file_id").references(() => wpUploadedFilesTable.id, { onDelete: "set null" }),
  sourceSheet: text("source_sheet"),
  sourcePage: integer("source_page"),
  reviewStatus: text("review_status").default("pending"),
  isLocked: boolean("is_locked").default(false),
  lockedAt: timestamp("locked_at"),
  lockedBy: integer("locked_by"),
  editedBy: integer("edited_by"),
  editedAt: timestamp("edited_at"),
  reasonForChange: text("reason_for_change"),
  versionNo: integer("version_no").default(1),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  uniqueIndex("wp_variables_session_code_idx").on(t.sessionId, t.variableCode),
  index("wp_variables_session_id_idx").on(t.sessionId),
  index("wp_variables_category_idx").on(t.sessionId, t.category),
]);

export const wpVariableChangeLogTable = pgTable("wp_variable_change_log", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  variableId: integer("variable_id").references(() => wpVariablesTable.id, { onDelete: "cascade" }),
  variableCode: varchar("variable_code", { length: 100 }),
  fieldName: text("field_name").notNull(),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  editedBy: integer("edited_by"),
  reason: text("reason"),
  sourceOfChange: text("source_of_change").default("manual"),
  createdAt: timestamp("created_at").defaultNow(),
}, (t) => [
  index("wp_var_changelog_session_id_idx").on(t.sessionId),
  index("wp_var_changelog_variable_id_idx").on(t.variableId),
]);

export const wpVariableDependencyRulesTable = pgTable("wp_variable_dependency_rules", {
  id: serial("id").primaryKey(),
  triggerVariableCode: varchar("trigger_variable_code", { length: 100 }).notNull(),
  conditionExpression: text("condition_expression"),
  impactedVariableCodesJson: jsonb("impacted_variable_codes_json"),
  impactedWorkingPapersJson: jsonb("impacted_working_papers_json"),
  impactedCalculationsJson: jsonb("impacted_calculations_json"),
  impactedRiskAreasJson: jsonb("impacted_risk_areas_json"),
  activeFlag: boolean("active_flag").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const wpExceptionLogTable = pgTable("wp_exception_log", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  headIndex: integer("head_index"),
  exceptionType: text("exception_type").notNull(),
  severity: text("severity").notNull().default("medium"),
  title: text("title").notNull(),
  description: text("description"),
  status: wpExceptionStatus("exception_log_status").notNull().default("open"),
  resolvedBy: integer("resolved_by"),
  resolvedAt: timestamp("resolved_at"),
  resolution: text("resolution"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_exception_log_session_id_idx").on(t.sessionId),
  index("wp_exception_log_status_idx").on(t.status),
]);

export const wpTrialBalanceLinesTable = pgTable("wp_trial_balance_lines", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  accountCode: text("account_code").notNull(),
  accountName: text("account_name").notNull(),
  classification: text("classification"),
  fsLineMapping: text("fs_line_mapping"),
  debit: decimal("debit", { precision: 15, scale: 2 }).default("0"),
  credit: decimal("credit", { precision: 15, scale: 2 }).default("0"),
  balance: decimal("balance", { precision: 15, scale: 2 }).default("0"),
  priorYearBalance: decimal("prior_year_balance", { precision: 15, scale: 2 }).default("0"),
  source: text("source").default("deterministic"),
  confidence: decimal("confidence", { precision: 5, scale: 2 }),
  isApproved: boolean("is_approved").default(false),
  hasException: boolean("has_exception").default(false),
  exceptionNote: text("exception_note"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_tb_lines_session_id_idx").on(t.sessionId),
  index("wp_tb_lines_account_code_idx").on(t.sessionId, t.accountCode),
]);

export const wpGlAccountsTable = pgTable("wp_gl_accounts", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  accountCode: text("account_code").notNull(),
  accountName: text("account_name").notNull(),
  accountType: text("account_type"),
  openingBalance: decimal("opening_balance", { precision: 15, scale: 2 }).default("0"),
  closingBalance: decimal("closing_balance", { precision: 15, scale: 2 }).default("0"),
  totalDebit: decimal("total_debit", { precision: 15, scale: 2 }).default("0"),
  totalCredit: decimal("total_credit", { precision: 15, scale: 2 }).default("0"),
  tbDebit: decimal("tb_debit", { precision: 15, scale: 2 }).default("0"),
  tbCredit: decimal("tb_credit", { precision: 15, scale: 2 }).default("0"),
  isReconciled: boolean("is_reconciled").default(false),
  isSynthetic: boolean("is_synthetic").default(false),
  generationRationale: text("generation_rationale"),
  transactionCountNote: text("transaction_count_note"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_gl_accounts_session_id_idx").on(t.sessionId),
  index("wp_gl_accounts_code_idx").on(t.sessionId, t.accountCode),
]);

export const wpGlEntriesTable = pgTable("wp_gl_entries", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  glAccountId: integer("gl_account_id").references(() => wpGlAccountsTable.id, { onDelete: "cascade" }),
  entryDate: text("entry_date").notNull(),
  voucherNo: text("voucher_no"),
  narration: text("narration"),
  debit: decimal("debit", { precision: 15, scale: 2 }).default("0"),
  credit: decimal("credit", { precision: 15, scale: 2 }).default("0"),
  runningBalance: decimal("running_balance", { precision: 15, scale: 2 }),
  month: integer("month"),
  isSynthetic: boolean("is_synthetic").default(false),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_gl_entries_session_id_idx").on(t.sessionId),
  index("wp_gl_entries_account_id_idx").on(t.glAccountId),
  index("wp_gl_entries_date_idx").on(t.sessionId, t.entryDate),
]);

export const wpHeadsTable = pgTable("wp_heads", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  headIndex: integer("head_index").notNull(),
  headName: text("head_name").notNull(),
  status: wpHeadStatus("head_status").notNull().default("locked"),
  papersIncluded: jsonb("papers_included"),
  outputType: text("output_type"),
  generatedAt: timestamp("generated_at"),
  validatedAt: timestamp("validated_at"),
  approvedAt: timestamp("approved_at"),
  approvedBy: integer("approved_by"),
  exportedAt: timestamp("exported_at"),
  exceptionsCount: integer("exceptions_count").default(0),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_heads_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_heads_session_head_idx").on(t.sessionId, t.headIndex),
]);

export const wpHeadDocumentsTable = pgTable("wp_head_documents", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  headId: integer("head_id").references(() => wpHeadsTable.id, { onDelete: "cascade" }).notNull(),
  paperCode: text("paper_code").notNull(),
  paperName: text("paper_name").notNull(),
  content: text("content"),
  outputFormat: text("output_format").default("word"),
  status: text("document_status").default("pending"),
  generatedAt: timestamp("generated_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_head_docs_session_id_idx").on(t.sessionId),
  index("wp_head_docs_head_id_idx").on(t.headId),
]);

export const wpExportJobsTable = pgTable("wp_export_jobs", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  headId: integer("head_id").references(() => wpHeadsTable.id, { onDelete: "cascade" }),
  exportType: text("export_type").notNull().default("head"),
  format: text("format"),
  fileName: text("file_name"),
  status: text("export_job_status").default("pending"),
  completedAt: timestamp("completed_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_export_jobs_session_id_idx").on(t.sessionId),
]);

export const auditEngineMasterTable = pgTable("audit_engine_master", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull().unique(),
  engagementId: varchar("engagement_id", { length: 50 }),
  clientName: text("client_name"),
  entityType: text("entity_type"),
  industryType: text("industry_type"),
  financialYearStart: text("financial_year_start"),
  financialYearEnd: text("financial_year_end"),
  reportingFramework: text("reporting_framework").default("IFRS"),
  auditType: text("audit_type").default("Statutory"),
  engagementStatus: text("engagement_status").default("Planning"),
  materialityAmount: decimal("materiality_amount", { precision: 18, scale: 2 }),
  performanceMateriality: decimal("performance_materiality", { precision: 18, scale: 2 }),
  trivialityThreshold: decimal("triviality_threshold", { precision: 18, scale: 2 }),
  riskLevelOverall: text("risk_level_overall").default("Medium"),
  goingConcernFlag: boolean("going_concern_flag").default(false),
  fraudRiskFlag: boolean("fraud_risk_flag").default(false),
  relatedPartyFlag: boolean("related_party_flag").default(false),
  lawsRegulationFlag: boolean("laws_regulation_flag").default(false),
  componentAuditFlag: boolean("component_audit_flag").default(false),
  groupAuditFlag: boolean("group_audit_flag").default(false),
  itSystemType: text("it_system_type").default("ERP"),
  internalAuditFlag: boolean("internal_audit_flag").default(false),
  useOfExpertFlag: boolean("use_of_expert_flag").default(false),
  samplingMethod: text("sampling_method").default("MUS"),
  dataSource: text("data_source").default("OCR"),
  confidenceLevel: decimal("confidence_level", { precision: 5, scale: 2 }),
  exceptionFlag: boolean("exception_flag").default(false),
  preparedBy: text("prepared_by"),
  reviewedBy: text("reviewed_by"),
  approvedBy: text("approved_by"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const wpTriggerDefsTable = pgTable("wp_trigger_defs", {
  id: serial("id").primaryKey(),
  wpCode: varchar("wp_code", { length: 20 }).notNull().unique(),
  wpName: text("wp_name").notNull(),
  triggerCondition: text("trigger_condition").notNull(),
  triggerDescription: text("trigger_description"),
  isaReference: text("isa_reference"),
  outputFormat: text("output_format").default("Word"),
  mandatoryFlag: boolean("mandatory_flag").default(true),
  category: text("category"),
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const wpTriggerSessionTable = pgTable("wp_trigger_session", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: varchar("wp_code", { length: 20 }).notNull(),
  triggered: boolean("triggered").default(false),
  triggerReason: text("trigger_reason"),
  status: text("status").default("pending"),
  preparedBy: text("prepared_by"),
  reviewedBy: text("reviewed_by"),
  completedAt: timestamp("completed_at"),
  conclusion: text("conclusion"),
  exceptionNote: text("exception_note"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_trigger_session_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_trigger_session_code_idx").on(t.sessionId, t.wpCode),
]);

export const assertionLinkageTable = pgTable("assertion_linkage", {
  id: serial("id").primaryKey(),
  accountType: text("account_type").notNull(),
  fsLineItem: text("fs_line_item"),
  assertion: text("assertion").notNull(),
  wpCode: varchar("wp_code", { length: 20 }),
  wpLink: text("wp_link"),
  testingProcedure: text("testing_procedure"),
  isaReference: text("isa_reference"),
  riskTag: text("risk_tag"),
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

export const samplingRulesTable = pgTable("sampling_rules", {
  id: serial("id").primaryKey(),
  riskLevel: text("risk_level").notNull(),
  materialityBand: text("materiality_band").notNull(),
  sampleSizeMin: integer("sample_size_min").notNull(),
  sampleSizeMax: integer("sample_size_max").notNull(),
  coveragePct: decimal("coverage_pct", { precision: 5, scale: 2 }),
  samplingMethod: text("sampling_method"),
  testingApproach: text("testing_approach"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const analyticsEngineTable = pgTable("analytics_engine", {
  id: serial("id").primaryKey(),
  ratioCode: varchar("ratio_code", { length: 30 }).notNull().unique(),
  ratioName: text("ratio_name").notNull(),
  formula: text("formula").notNull(),
  numeratorField: text("numerator_field"),
  denominatorField: text("denominator_field"),
  thresholdMin: decimal("threshold_min", { precision: 10, scale: 4 }),
  thresholdMax: decimal("threshold_max", { precision: 10, scale: 4 }),
  thresholdDescription: text("threshold_description"),
  wpTrigger: varchar("wp_trigger", { length: 20 }),
  category: text("category"),
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

export const analyticsSessionTable = pgTable("analytics_session", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  ratioCode: varchar("ratio_code", { length: 30 }).notNull(),
  computedValue: decimal("computed_value", { precision: 15, scale: 4 }),
  priorYearValue: decimal("prior_year_value", { precision: 15, scale: 4 }),
  variance: decimal("variance", { precision: 15, scale: 4 }),
  breached: boolean("breached").default(false),
  explanation: text("explanation"),
  wpTriggered: boolean("wp_triggered").default(false),
  reviewedBy: text("reviewed_by"),
  conclusion: text("conclusion"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("analytics_session_session_id_idx").on(t.sessionId),
  uniqueIndex("analytics_session_ratio_idx").on(t.sessionId, t.ratioCode),
]);

export const controlMatrixTable = pgTable("control_matrix", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  processName: text("process_name").notNull(),
  controlDescription: text("control_description").notNull(),
  controlFrequency: text("control_frequency"),
  controlOwner: text("control_owner"),
  testType: text("test_type").default("ToC"),
  sampleSize: integer("sample_size"),
  testingResult: text("testing_result"),
  exceptionCount: integer("exception_count").default(0),
  relatedWpCode: varchar("related_wp_code", { length: 20 }),
  isaReference: text("isa_reference"),
  testedBy: text("tested_by"),
  conclusion: text("conclusion"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("control_matrix_session_id_idx").on(t.sessionId),
]);

export const evidenceLogTable = pgTable("evidence_log", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: varchar("wp_code", { length: 20 }),
  headId: integer("head_id").references(() => wpHeadsTable.id, { onDelete: "set null" }),
  evidenceId: varchar("evidence_id", { length: 50 }),
  documentType: text("document_type"),
  documentRef: text("document_ref"),
  source: text("source").default("Client"),
  description: text("description"),
  obtainedDate: text("obtained_date"),
  verifiedFlag: boolean("verified_flag").default(false),
  verifiedBy: text("verified_by"),
  reviewerComment: text("reviewer_comment"),
  exceptionFlag: boolean("exception_flag").default(false),
  attachmentPath: text("attachment_path"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("evidence_log_session_id_idx").on(t.sessionId),
  index("evidence_log_wp_code_idx").on(t.sessionId, t.wpCode),
]);

export const reconEngineTable = pgTable("recon_engine", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  checkName: text("check_name").notNull(),
  sourceA: text("source_a").notNull(),
  sourceB: text("source_b").notNull(),
  amountA: decimal("amount_a", { precision: 18, scale: 2 }).default("0"),
  amountB: decimal("amount_b", { precision: 18, scale: 2 }).default("0"),
  difference: decimal("difference", { precision: 18, scale: 2 }).default("0"),
  passed: boolean("passed").default(false),
  rule: text("rule"),
  notes: text("notes"),
  runAt: timestamp("run_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("recon_engine_session_id_idx").on(t.sessionId),
]);

export const wpLibraryMasterTable = pgTable("wp_library_master", {
  id: serial("id").primaryKey(),
  wpCode: varchar("wp_code", { length: 20 }).notNull().unique(),
  wpPhase: text("wp_phase"),
  wpTitle: text("wp_title").notNull(),
  wpCategory: text("wp_category"),
  isaReference: text("isa_reference"),
  secondaryReference: text("secondary_reference"),
  codeFamily: varchar("code_family", { length: 4 }),
  displayOrder: integer("display_order").default(0),
  triggerEntityType: text("trigger_entity_type"),
  triggerIndustry: text("trigger_industry"),
  triggerRisk: text("trigger_risk"),
  triggerFsHead: text("trigger_fs_head"),
  triggerControlMode: text("trigger_control_mode"),
  triggerMateriality: text("trigger_materiality"),
  mandatoryFlag: boolean("mandatory_flag").default(false),
  outputFormat: text("output_format").default("Word"),
  parentWpCode: varchar("parent_wp_code", { length: 20 }),
  linkedWpCodes: text("linked_wp_codes"),
  linkedAssertion: text("linked_assertion"),
  linkedAuditProcedureType: text("linked_audit_procedure_type"),
  linkedEvidenceType: text("linked_evidence_type"),
  linkedReportArea: text("linked_report_area"),
  pakistanLawTag: text("pakistan_law_tag"),
  reviewerLevel: text("reviewer_level"),
  autoGenerateFlag: boolean("auto_generate_flag").default(false),
  aiInputSource: text("ai_input_source"),
  status: text("status").default("Draft"),
  versionNo: text("version_no").default("v1.0"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_library_master_phase_idx").on(t.wpPhase),
  index("wp_library_master_family_idx").on(t.codeFamily),
]);

export const wpLibrarySessionTable = pgTable("wp_library_session", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: varchar("wp_code", { length: 20 }).notNull(),
  wpTitle: text("wp_title"),
  wpPhase: text("wp_phase"),
  wpCategory: text("wp_category"),
  isaReference: text("isa_reference"),
  triggerReason: text("trigger_reason"),
  mandatoryFlag: boolean("mandatory_flag").default(false),
  status: text("status").default("Pending"),
  preparedBy: text("prepared_by"),
  reviewedBy: text("reviewed_by"),
  approvedBy: text("approved_by"),
  preparedDate: text("prepared_date"),
  reviewedDate: text("reviewed_date"),
  approvedDate: text("approved_date"),
  conclusion: text("conclusion"),
  outputFormat: text("output_format"),
  reviewerLevel: text("reviewer_level"),
  evidenceCount: integer("evidence_count").default(0),
  autoGenerateFlag: boolean("auto_generate_flag").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_library_session_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_library_session_code_idx").on(t.sessionId, t.wpCode),
]);

export const wpJournalImportTable = pgTable("wp_journal_import", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  journalId: text("journal_id"),
  entryNo: text("entry_no"),
  entryDate: text("entry_date"),
  period: text("period"),
  voucherType: text("voucher_type"),
  documentNo: text("document_no"),
  narration: text("narration"),
  accountCode: text("account_code"),
  accountName: text("account_name"),
  costCenter: text("cost_center"),
  department: text("department"),
  projectCode: text("project_code"),
  partyCode: text("party_code"),
  debitAmount: decimal("debit_amount", { precision: 15, scale: 2 }).default("0"),
  creditAmount: decimal("credit_amount", { precision: 15, scale: 2 }).default("0"),
  currency: text("currency").default("PKR"),
  exchangeRate: decimal("exchange_rate", { precision: 10, scale: 6 }).default("1"),
  baseDebit: decimal("base_debit", { precision: 15, scale: 2 }).default("0"),
  baseCredit: decimal("base_credit", { precision: 15, scale: 2 }).default("0"),
  sourceSystem: text("source_system"),
  sourceFileName: text("source_file_name"),
  postedFlag: boolean("posted_flag").default(true),
  dataSource: text("data_source"),
  confidenceScore: decimal("confidence_score", { precision: 5, scale: 2 }),
  exceptionFlag: boolean("exception_flag").default(false),
  exceptionNote: text("exception_note"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_journal_import_session_id_idx").on(t.sessionId),
  index("wp_journal_import_account_idx").on(t.sessionId, t.accountCode),
  index("wp_journal_import_date_idx").on(t.sessionId, t.entryDate),
]);

export const wpFsExtractionTable = pgTable("wp_fs_extraction", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  extractionId: text("extraction_id"),
  sourceFileName: text("source_file_name"),
  sourceFileType: text("source_file_type"),
  pageNo: integer("page_no"),
  statementType: text("statement_type"),
  sectionName: text("section_name"),
  lineItemText: text("line_item_text"),
  amountCurrent: decimal("amount_current", { precision: 15, scale: 2 }),
  amountPrior: decimal("amount_prior", { precision: 15, scale: 2 }),
  currency: text("currency").default("PKR"),
  signConvention: text("sign_convention"),
  extractionMethod: text("extraction_method"),
  confidenceScore: decimal("confidence_score", { precision: 5, scale: 2 }),
  normalizedText: text("normalized_text"),
  exceptionFlag: boolean("exception_flag").default(false),
  exceptionNote: text("exception_note"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_fs_extraction_session_id_idx").on(t.sessionId),
]);

export const wpFsMappingTable = pgTable("wp_fs_mapping", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  mappingId: text("mapping_id"),
  extractionId: text("extraction_id"),
  statementType: text("statement_type"),
  fsLineItem: text("fs_line_item"),
  fsNoteNo: text("fs_note_no"),
  currentAmount: decimal("current_amount", { precision: 15, scale: 2 }),
  priorAmount: decimal("prior_amount", { precision: 15, scale: 2 }),
  accountCode: text("account_code"),
  accountName: text("account_name"),
  mappingFsLine: text("mapping_fs_line"),
  mappingMethod: text("mapping_method"),
  mappingConfidence: decimal("mapping_confidence", { precision: 5, scale: 2 }),
  reconciliationFlag: boolean("reconciliation_flag").default(false),
  exceptionFlag: boolean("exception_flag").default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_fs_mapping_session_id_idx").on(t.sessionId),
]);

export const wpMasterCoaTable = pgTable("wp_master_coa", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  accountCode: varchar("account_code", { length: 20 }).notNull(),
  parentCode: varchar("parent_code", { length: 20 }),
  accountName: text("account_name").notNull(),
  fsHead: text("fs_head"),
  fsSubHead: text("fs_sub_head"),
  accountType: text("account_type"),
  normalBalance: text("normal_balance"),
  industryTag: text("industry_tag"),
  entityTypeTag: text("entity_type_tag"),
  ifrsReference: text("ifrs_reference"),
  taxTreatment: text("tax_treatment"),
  isControlAccount: boolean("is_control_account").default(false),
  isSubLedger: boolean("is_sub_ledger").default(false),
  openingBalance: decimal("opening_balance", { precision: 15, scale: 2 }).default("0"),
  debitTotal: decimal("debit_total", { precision: 15, scale: 2 }).default("0"),
  creditTotal: decimal("credit_total", { precision: 15, scale: 2 }).default("0"),
  closingBalance: decimal("closing_balance", { precision: 15, scale: 2 }).default("0"),
  priorYearBalance: decimal("prior_year_balance", { precision: 15, scale: 2 }).default("0"),
  variance: decimal("variance", { precision: 15, scale: 2 }).default("0"),
  materialityTag: text("materiality_tag"),
  riskTag: text("risk_tag"),
  assertionTag: text("assertion_tag"),
  relatedPartyFlag: boolean("related_party_flag").default(false),
  cashFlowTag: text("cash_flow_tag"),
  mappingGlCode: text("mapping_gl_code"),
  mappingFsLine: text("mapping_fs_line"),
  workingPaperCode: text("working_paper_code"),
  reconciliationFlag: boolean("reconciliation_flag").default(false),
  dataSource: text("data_source"),
  confidenceScore: decimal("confidence_score", { precision: 5, scale: 2 }),
  exceptionFlag: boolean("exception_flag").default(false),
  notes: text("notes"),
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_master_coa_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_master_coa_session_code_idx").on(t.sessionId, t.accountCode),
]);

export const wpTriggerRulesTable = pgTable("wp_trigger_rules", {
  id: serial("id").primaryKey(),
  ruleName: text("rule_name").notNull(),
  ruleDescription: text("rule_description"),
  codeFamily: varchar("code_family", { length: 4 }),
  entityType: text("entity_type"),
  industry: text("industry"),
  risk: text("risk"),
  fsHead: text("fs_head"),
  controlMode: text("control_mode"),
  materialityLevel: text("materiality_level"),
  activateWpCodes: text("activate_wp_codes").notNull(),
  procedureType: text("procedure_type"),
  assertionLink: text("assertion_link"),
  samplingRate: decimal("sampling_rate", { precision: 5, scale: 2 }),
  priority: integer("priority").default(50),
  mandatoryOverride: boolean("mandatory_override").default(false),
  isaJustification: text("isa_justification"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const wpValidationResultTable = pgTable("wp_validation_result", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  runAt: timestamp("run_at").defaultNow(),
  overallPass: boolean("overall_pass").default(false),
  tbFsPass: boolean("tb_fs_pass").default(false),
  tbFsDifference: decimal("tb_fs_difference", { precision: 15, scale: 2 }),
  tbFsNote: text("tb_fs_note"),
  glTbPass: boolean("gl_tb_pass").default(false),
  glTbNote: text("gl_tb_note"),
  mandatoryVarsPass: boolean("mandatory_vars_pass").default(false),
  missingVars: text("missing_vars"),
  confidencePass: boolean("confidence_pass").default(false),
  lowConfidenceCount: integer("low_confidence_count").default(0),
  lowConfidenceItems: text("low_confidence_items"),
  mandatoryWpsPass: boolean("mandatory_wps_pass").default(false),
  incompleteWpCount: integer("incomplete_wp_count").default(0),
  coaTbPass: boolean("coa_tb_pass").default(false),
  unmappedAccountCount: integer("unmapped_account_count").default(0),
  blockedReasons: text("blocked_reasons"),
  warnings: text("warnings"),
  generationAllowed: boolean("generation_allowed").default(false),
  validatedBy: text("validated_by"),
  notes: text("notes"),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_validation_result_session_id_idx").on(t.sessionId),
]);

export const wpExceptionsTable = pgTable("wp_exceptions", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  exceptionCode: text("exception_code"),
  exceptionType: text("exception_type").notNull(),
  severity: text("severity").default("Medium"),
  sourceArea: text("source_area"),
  referenceCode: text("reference_code"),
  description: text("description").notNull(),
  detail: text("detail"),
  isaReference: text("isa_reference"),
  resolvedFlag: boolean("resolved_flag").default(false),
  resolvedBy: text("resolved_by"),
  resolvedAt: timestamp("resolved_at"),
  resolutionNote: text("resolution_note"),
  autoFlagged: boolean("auto_flagged").default(true),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_exceptions_session_id_idx").on(t.sessionId),
  index("wp_exceptions_type_idx").on(t.sessionId, t.exceptionType),
  index("wp_exceptions_severity_idx").on(t.severity),
]);

export const wpSessionLockTable = pgTable("wp_session_lock", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull().unique(),
  lockedAt: timestamp("locked_at").defaultNow(),
  lockedBy: text("locked_by").notNull(),
  lockLevel: text("lock_level").default("Partner"),
  lockJustification: text("lock_justification"),
  preArchiveValidationPassed: boolean("pre_archive_validation_passed").default(false),
  archiveRef: text("archive_ref"),
  retentionEndDate: text("retention_end_date"),
  eqcrCompleted: boolean("eqcr_completed").default(false),
  eqcrBy: text("eqcr_by"),
  unlockAllowed: boolean("unlock_allowed").default(false),
  unlockedAt: timestamp("unlocked_at"),
  unlockedBy: text("unlocked_by"),
  unlockReason: text("unlock_reason"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const wpExecutionTable = pgTable("wp_execution", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: varchar("wp_code", { length: 20 }).notNull(),
  wpTitle: text("wp_title").notNull().default("Untitled"),
  wpPhase: text("wp_phase"),
  wpCategory: text("wp_category"),
  isaReference: text("isa_reference"),
  secondaryReference: text("secondary_reference"),
  objective: text("objective"),
  assertions: jsonb("assertions"),
  riskLevel: text("risk_level").default("Medium"),
  riskDescription: text("risk_description"),
  linkedRisks: jsonb("linked_risks"),
  procedures: jsonb("procedures"),
  samplingMethod: text("sampling_method"),
  populationSize: integer("population_size"),
  sampleSize: integer("sample_size"),
  samplingCriteria: text("sampling_criteria"),
  samplingItems: jsonb("sampling_items"),
  workPerformed: jsonb("work_performed"),
  evidenceItems: jsonb("evidence_items"),
  findings: jsonb("findings"),
  misstatements: jsonb("misstatements"),
  totalMisstatementAmount: decimal("total_misstatement_amount", { precision: 15, scale: 2 }).default("0"),
  analyticalData: jsonb("analytical_data"),
  professionalJudgment: text("professional_judgment"),
  staffConclusion: text("staff_conclusion"),
  staffConclusionDate: text("staff_conclusion_date"),
  staffName: text("staff_name"),
  seniorConclusion: text("senior_conclusion"),
  seniorConclusionDate: text("senior_conclusion_date"),
  seniorName: text("senior_name"),
  managerConclusion: text("manager_conclusion"),
  managerConclusionDate: text("manager_conclusion_date"),
  managerName: text("manager_name"),
  partnerConclusion: text("partner_conclusion"),
  partnerConclusionDate: text("partner_conclusion_date"),
  partnerName: text("partner_name"),
  reviewNotes: jsonb("review_notes"),
  isaChecklist: jsonb("isa_checklist"),
  tbGlCrossRefs: jsonb("tb_gl_cross_refs"),
  signOffs: jsonb("sign_offs"),
  proceduresComplete: boolean("procedures_complete").default(false),
  evidenceComplete: boolean("evidence_complete").default(false),
  conclusionsComplete: boolean("conclusions_complete").default(false),
  validationErrors: jsonb("validation_errors"),
  status: text("status").default("not_started"),
  isLocked: boolean("is_locked").default(false),
  lockedAt: timestamp("locked_at"),
  lockedBy: text("locked_by"),
  createdBy: text("created_by"),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_execution_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_execution_session_wp_idx").on(t.sessionId, t.wpCode),
  index("wp_execution_status_idx").on(t.status),
]);

export const wpOutputJobTable = pgTable("wp_output_job", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  jobType: text("job_type").notNull(),
  status: text("status").default("queued"),
  triggeredBy: text("triggered_by"),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  outputPath: text("output_path"),
  outputSize: integer("output_size"),
  recordCount: integer("record_count"),
  errorMessage: text("error_message"),
  metadata: text("metadata"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_output_job_session_id_idx").on(t.sessionId),
  index("wp_output_job_status_idx").on(t.status),
]);

export const wpComplianceDocTable = pgTable("wp_compliance_doc", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  docType: text("doc_type").notNull(),
  docCode: text("doc_code").notNull(),
  isaReference: text("isa_reference"),
  generatedContent: jsonb("generated_content"),
  generatedAt: timestamp("generated_at"),
  generatedBy: text("generated_by"),
  version: integer("version").default(1),
  status: text("status").default("pending"),
  signatoryName: text("signatory_name"),
  signatoryDesignation: text("signatory_designation"),
  signingDate: text("signing_date"),
  signedBy: text("signed_by"),
  signedAt: timestamp("signed_at"),
  rejectionReason: text("rejection_reason"),
  checklistItems: jsonb("checklist_items"),
  checklistCompletedAt: timestamp("checklist_completed_at"),
  checklistCompletedBy: text("checklist_completed_by"),
  teamMemberConfirmations: jsonb("team_member_confirmations"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_compliance_doc_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_compliance_doc_session_code_idx").on(t.sessionId, t.docCode),
]);

export const wpAuditChainTable = pgTable("wp_audit_chain", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: text("wp_code").notNull(),
  fsArea: text("fs_area").notNull(),
  riskId: text("risk_id").notNull(),
  riskDescription: text("risk_description").notNull(),
  riskType: text("risk_type").notNull(),
  isaRiskRef: text("isa_risk_ref"),
  riskLevel: text("risk_level").default("medium"),
  riskResponse: text("risk_response"),
  assertions: jsonb("assertions"),
  assertionCoverage: text("assertion_coverage"),
  procedureId: text("procedure_id").notNull(),
  procedureDescription: text("procedure_description").notNull(),
  procedureNature: text("procedure_nature"),
  procedureIsaRef: text("procedure_isa_ref"),
  procedureIsaClause: text("procedure_isa_clause"),
  procedureTiming: text("procedure_timing"),
  procedurePerformedBy: text("procedure_performed_by"),
  procedurePerformedDate: text("procedure_performed_date"),
  procedureStatus: text("procedure_status").default("planned"),
  evidenceIds: jsonb("evidence_ids"),
  evidenceType: text("evidence_type"),
  evidenceReliability: text("evidence_reliability"),
  evidenceSufficiency: text("evidence_sufficiency"),
  tickMarkCode: text("tick_mark_code"),
  tickMarkMeaning: text("tick_mark_meaning"),
  resultSummary: text("result_summary"),
  exceptionsFound: integer("exceptions_found").default(0),
  exceptionDetails: jsonb("exception_details"),
  misstatementAmount: decimal("misstatement_amount", { precision: 18, scale: 2 }).default("0"),
  misstatementType: text("misstatement_type"),
  conclusion: text("conclusion"),
  conclusionNarrative: text("conclusion_narrative"),
  impactOnOpinion: text("impact_on_opinion"),
  conclusionIsaRef: text("conclusion_isa_ref"),
  furtherActionRequired: boolean("further_action_required").default(false),
  furtherActionDetail: text("further_action_detail"),
  chainComplete: boolean("chain_complete").default(false),
  chainValidatedAt: timestamp("chain_validated_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_audit_chain_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_audit_chain_procedure_idx").on(t.sessionId, t.procedureId),
  index("wp_audit_chain_wp_code_idx").on(t.sessionId, t.wpCode),
  index("wp_audit_chain_fs_area_idx").on(t.sessionId, t.fsArea),
]);

export const wpIsaClauseRefTable = pgTable("wp_isa_clause_ref", {
  id: serial("id").primaryKey(),
  isaStandard: text("isa_standard").notNull(),
  clauseNumber: text("clause_number").notNull(),
  fullRef: text("full_ref").notNull(),
  clauseText: text("clause_text").notNull(),
  category: text("category"),
  applicableTo: text("applicable_to"),
  mandatory: boolean("mandatory").default(false),
  mappedProcedureType: text("mapped_procedure_type"),
  createdAt: timestamp("created_at").defaultNow(),
}, (t) => [
  uniqueIndex("wp_isa_clause_ref_std_clause_idx").on(t.isaStandard, t.clauseNumber),
]);

export const wpTickMarkTable = pgTable("wp_tick_mark", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  symbol: text("symbol").notNull(),
  meaning: text("meaning").notNull(),
  color: text("color"),
  category: text("category"),
  isStandard: boolean("is_standard").default(true),
  usageCount: integer("usage_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_tick_mark_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_tick_mark_session_symbol_idx").on(t.sessionId, t.symbol),
]);

export const wpTickMarkUsageTable = pgTable("wp_tick_mark_usage", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  tickMarkId: integer("tick_mark_id").references(() => wpTickMarkTable.id, { onDelete: "cascade" }),
  symbol: text("symbol").notNull(),
  wpCode: text("wp_code").notNull(),
  lineRef: text("line_ref"),
  accountCode: text("account_code"),
  amount: decimal("amount", { precision: 18, scale: 2 }),
  appliedBy: text("applied_by"),
  appliedAt: timestamp("applied_at").defaultNow(),
  evidenceRef: text("evidence_ref"),
  notes: text("notes"),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_tick_mark_usage_session_id_idx").on(t.sessionId),
  index("wp_tick_mark_usage_wp_code_idx").on(t.sessionId, t.wpCode),
]);

export const wpReviewNoteTable = pgTable("wp_review_note", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: text("wp_code"),
  headIndex: integer("head_index"),
  reviewLevel: text("review_level").notNull(),
  reviewerName: text("reviewer_name").notNull(),
  reviewerId: integer("reviewer_id"),
  noteType: text("note_type").default("query"),
  priority: text("priority").default("medium"),
  subject: text("subject").notNull(),
  detail: text("detail").notNull(),
  isaReference: text("isa_reference"),
  status: text("status").default("open"),
  responseBy: text("response_by"),
  responseDate: timestamp("response_date"),
  responseText: text("response_text"),
  clearedBy: text("cleared_by"),
  clearedDate: timestamp("cleared_date"),
  clearanceNote: text("clearance_note"),
  escalatedTo: text("escalated_to"),
  escalationReason: text("escalation_reason"),
  blocksSignOff: boolean("blocks_sign_off").default(false),
  blocksExport: boolean("blocks_export").default(false),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_review_note_session_id_idx").on(t.sessionId),
  index("wp_review_note_status_idx").on(t.sessionId, t.status),
  index("wp_review_note_wp_code_idx").on(t.sessionId, t.wpCode),
]);

export const wpVersionHistoryTable = pgTable("wp_version_history", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  fieldName: text("field_name"),
  version: integer("version").notNull(),
  changeType: text("change_type").notNull(),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  reason: text("reason"),
  changedBy: text("changed_by"),
  changedByRole: text("changed_by_role"),
  ipAddress: text("ip_address"),
  isImmutable: boolean("is_immutable").default(true),
  createdAt: timestamp("created_at").defaultNow(),
}, (t) => [
  index("wp_version_history_session_id_idx").on(t.sessionId),
  index("wp_version_history_entity_idx").on(t.sessionId, t.entityType, t.entityId),
]);

export const wpLeadScheduleTable = pgTable("wp_lead_schedule", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpArea: text("wp_area").notNull(),
  wpCode: text("wp_code"),
  scheduleRef: text("schedule_ref").notNull(),
  fsSection: text("fs_section"),
  majorHead: text("major_head"),
  lineItem: text("line_item"),
  noteNo: text("note_no"),
  openingBalance: decimal("opening_balance", { precision: 18, scale: 2 }).default("0"),
  additions: decimal("additions", { precision: 18, scale: 2 }).default("0"),
  disposals: decimal("disposals", { precision: 18, scale: 2 }).default("0"),
  transfers: decimal("transfers", { precision: 18, scale: 2 }).default("0"),
  revaluation: decimal("revaluation", { precision: 18, scale: 2 }).default("0"),
  depreciation: decimal("depreciation", { precision: 18, scale: 2 }).default("0"),
  impairment: decimal("impairment", { precision: 18, scale: 2 }).default("0"),
  closingBalance: decimal("closing_balance", { precision: 18, scale: 2 }).default("0"),
  priorYear: decimal("prior_year", { precision: 18, scale: 2 }).default("0"),
  variance: decimal("variance", { precision: 18, scale: 2 }).default("0"),
  variancePct: decimal("variance_pct", { precision: 8, scale: 2 }).default("0"),
  tbAccountCodes: jsonb("tb_account_codes"),
  glCrossRef: text("gl_cross_ref"),
  fsCrossRef: text("fs_cross_ref"),
  wpCrossRefs: jsonb("wp_cross_refs"),
  tickMarks: jsonb("tick_marks"),
  riskLevel: text("risk_level"),
  materialityFlag: boolean("materiality_flag").default(false),
  auditConclusion: text("audit_conclusion"),
  status: text("status").default("draft"),
  preparedBy: text("prepared_by"),
  reviewedBy: text("reviewed_by"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_lead_schedule_session_id_idx").on(t.sessionId),
  index("wp_lead_schedule_wp_area_idx").on(t.sessionId, t.wpArea),
]);

export const wpFsNoteMappingTable = pgTable("wp_fs_note_mapping", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  noteNo: text("note_no").notNull(),
  noteTitle: text("note_title").notNull(),
  fsLineItems: jsonb("fs_line_items"),
  tbAccountCodes: jsonb("tb_account_codes"),
  totalCY: decimal("total_cy", { precision: 18, scale: 2 }),
  totalPY: decimal("total_py", { precision: 18, scale: 2 }),
  variance: decimal("variance", { precision: 18, scale: 2 }),
  wpCrossRef: text("wp_cross_ref"),
  disclosureStatus: text("disclosure_status").default("pending"),
  aiGeneratedNote: jsonb("ai_generated_note"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_fs_note_mapping_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_fs_note_mapping_note_idx").on(t.sessionId, t.noteNo),
]);

export const wpComplianceGateTable = pgTable("wp_compliance_gate", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  gateCode: text("gate_code").notNull(),
  gateName: text("gate_name").notNull(),
  category: text("category").notNull(),
  standard: text("standard"),
  checkDescription: text("check_description").notNull(),
  checkType: text("check_type").default("mandatory"),
  clauseRef: text("clause_ref"),
  status: text("status").default("pending"),
  blocking: boolean("blocking").default(false),
  failureDetail: text("failure_detail"),
  remediationAction: text("remediation_action"),
  overrideBy: text("override_by"),
  overrideReason: text("override_reason"),
  overrideDate: timestamp("override_date"),
  lastCheckedAt: timestamp("last_checked_at"),
  passedAt: timestamp("passed_at"),
  applicablePhase: text("applicable_phase"),
  headIndex: integer("head_index"),
  wpCode: text("wp_code"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_compliance_gate_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_compliance_gate_code_idx").on(t.sessionId, t.gateCode),
]);

export const wpSamplingDetailTable = pgTable("wp_sampling_detail", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => wpSessionsTable.id, { onDelete: "cascade" }).notNull(),
  wpCode: text("wp_code").notNull(),
  fsArea: text("fs_area").notNull(),
  samplingMethod: text("sampling_method").notNull(),
  populationDescription: text("population_description"),
  populationSize: integer("population_size"),
  populationValuePkr: decimal("population_value_pkr", { precision: 18, scale: 2 }).default("0"),
  stratificationApplied: boolean("stratification_applied").default(false),
  strata: jsonb("strata"),
  keyItemThreshold: decimal("key_item_threshold", { precision: 18, scale: 2 }),
  keyItemCount: integer("key_item_count"),
  keyItemValue: decimal("key_item_value", { precision: 18, scale: 2 }),
  confidenceLevel: decimal("confidence_level", { precision: 5, scale: 2 }),
  tolerableError: decimal("tolerable_error", { precision: 18, scale: 2 }),
  expectedError: decimal("expected_error", { precision: 18, scale: 2 }),
  sampleSize: integer("sample_size"),
  itemsTested: integer("items_tested"),
  exceptionsFound: integer("exceptions_found"),
  exceptionRate: decimal("exception_rate", { precision: 8, scale: 4 }),
  projectedMisstatement: decimal("projected_misstatement", { precision: 18, scale: 2 }),
  conclusion: text("conclusion"),
  conclusionBasis: text("conclusion_basis"),
  isaRef: text("isa_ref").default("ISA 530"),
  status: text("status").default("planned"),
  preparedBy: text("prepared_by"),
  reviewedBy: text("reviewed_by"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (t) => [
  index("wp_sampling_detail_session_id_idx").on(t.sessionId),
  uniqueIndex("wp_sampling_detail_wp_fs_idx").on(t.sessionId, t.wpCode, t.fsArea),
]);
